apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# quando o kustomize for customizar, vai ser os seguintes recursos abaixo
resources:
  - deployment.yaml
  - service.yaml

# o que vai ser customizado 
images: 
- name: go-server # antiga imagem
  newName: barafaskt/go-gitops  # nova imagem
  newTag: qualquerTag # nova tag | vamos mudar com a action do github actions